import type { Question } from '@lamo-trivia/shared';

export const HARRY_POTTER_QUESTIONS: Question[] = [
  {
    id: 'hp-001',
    text: 'What is the name of the train that takes students to Hogwarts?',
    options: ['The Hogwarts Express', 'The Wizarding Line', 'The Magical Express', 'The Knight Bus'],
    correctIndex: 0,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-002',
    text: 'What position does Harry play on his Quidditch team?',
    options: ['Chaser', 'Beater', 'Seeker', 'Keeper'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-003',
    text: 'What is the name of Hagrid\'s three-headed dog?',
    options: ['Fang', 'Norbert', 'Fluffy', 'Buckbeak'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-004',
    text: 'Which house at Hogwarts does Draco Malfoy belong to?',
    options: ['Gryffindor', 'Slytherin', 'Ravenclaw', 'Hufflepuff'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-005',
    text: 'What does the Mirror of Erised show?',
    options: ['The future', 'The past', 'Your deepest desire', 'Your worst fear'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-006',
    text: 'What type of dragon does Harry face in the Triwizard Tournament?',
    options: ['Norwegian Ridgeback', 'Hungarian Horntail', 'Swedish Short-Snout', 'Common Welsh Green'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-007',
    text: 'What is the core of Harry\'s wand?',
    options: ['Dragon heartstring', 'Unicorn hair', 'Phoenix feather', 'Veela hair'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-008',
    text: 'Who is the Half-Blood Prince?',
    options: ['Voldemort', 'Dumbledore', 'Snape', 'Sirius Black'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-009',
    text: 'What form does Harry\'s Patronus take?',
    options: ['A stag', 'A wolf', 'An otter', 'A phoenix'],
    correctIndex: 0,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-010',
    text: 'What is the name of the Weasley family home?',
    options: ['The Hollow', 'The Burrow', 'The Den', 'The Warren'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-011',
    text: 'Which spell is used to disarm an opponent?',
    options: ['Stupefy', 'Expelliarmus', 'Petrificus Totalus', 'Impedimenta'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-012',
    text: 'What is Voldemort\'s real name?',
    options: ['Tom Marvolo Riddle', 'Salazar Slytherin', 'Gellert Grindelwald', 'Marvolo Gaunt'],
    correctIndex: 0,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-013',
    text: 'How many Horcruxes did Voldemort intentionally create?',
    options: ['5', '6', '7', '8'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-014',
    text: 'What potion allows you to take on the appearance of someone else?',
    options: ['Veritaserum', 'Felix Felicis', 'Amortentia', 'Polyjuice Potion'],
    correctIndex: 3,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-015',
    text: 'Who was the Prisoner of Azkaban?',
    options: ['Barty Crouch Jr.', 'Bellatrix Lestrange', 'Sirius Black', 'Peter Pettigrew'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-016',
    text: 'What subject does Professor McGonagall teach?',
    options: ['Potions', 'Charms', 'Transfiguration', 'Defense Against the Dark Arts'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-017',
    text: 'What is the name of the Hogwarts poltergeist?',
    options: ['Nearly Headless Nick', 'The Bloody Baron', 'Moaning Myrtle', 'Peeves'],
    correctIndex: 3,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-018',
    text: 'What do you need to say to open the Marauder\'s Map?',
    options: ['Open sesame', 'I solemnly swear that I am up to no good', 'Reveal your secrets', 'Alohomora'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-019',
    text: 'What animal can Ron\'s pet Scabbers transform into?',
    options: ['A dog', 'A cat', 'A human', 'A snake'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-020',
    text: 'Which Deathly Hallow did Harry possess first?',
    options: ['The Elder Wand', 'The Resurrection Stone', 'The Cloak of Invisibility', 'None of them'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-021',
    text: 'What creature guards the vaults at Gringotts?',
    options: ['Trolls', 'Goblins', 'Dragons', 'House-elves'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-022',
    text: 'What is the name of Dumbledore\'s phoenix?',
    options: ['Hedwig', 'Errol', 'Fawkes', 'Hermes'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-023',
    text: 'Which spell produces light from the tip of a wand?',
    options: ['Lumos', 'Nox', 'Incendio', 'Expecto Patronum'],
    correctIndex: 0,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-024',
    text: 'What is the name of the house-elf who tries to warn Harry not to return to Hogwarts?',
    options: ['Kreacher', 'Winky', 'Dobby', 'Hokey'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-025',
    text: 'Where is the entrance to the Chamber of Secrets?',
    options: ['The Forbidden Forest', 'Moaning Myrtle\'s bathroom', 'The Room of Requirement', 'Dumbledore\'s office'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-026',
    text: 'What is the name of Hagrid\'s giant half-brother?',
    options: ['Grawp', 'Fridwulfa', 'Karkus', 'Golgomath'],
    correctIndex: 0,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-027',
    text: 'Who killed Sirius Black?',
    options: ['Voldemort', 'Lucius Malfoy', 'Bellatrix Lestrange', 'Snape'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-028',
    text: 'What street do the Dursleys live on?',
    options: ['Spinner\'s End', 'Magnolia Crescent', 'Privet Drive', 'Grimmauld Place'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-029',
    text: 'What is Hermione\'s Patronus?',
    options: ['A cat', 'An otter', 'A hare', 'A doe'],
    correctIndex: 1,
    categoryId: 'harry-potter',
  },
  {
    id: 'hp-030',
    text: 'Which Horcrux was hidden in the Room of Requirement?',
    options: ['Hufflepuff\'s Cup', 'Slytherin\'s Locket', 'Ravenclaw\'s Diadem', 'The Diary'],
    correctIndex: 2,
    categoryId: 'harry-potter',
  },
];
