export interface Riddle {
  id: string;
  text: string;
  answer: string; // uppercase, max 10 characters
  hint?: string;
}

// Family-friendly riddles with short answers (max 10 chars) for Wordle-style guessing
export const RIDDLES: Riddle[] = [
  { id: 'r1', text: 'I have hands but I can\'t clap. What am I?', answer: 'CLOCK', hint: 'Tick tock' },
  { id: 'r2', text: 'I have a head and a tail but no body. What am I?', answer: 'COIN', hint: 'Found in pockets' },
  { id: 'r3', text: 'What has keys but no locks?', answer: 'PIANO', hint: 'Makes music' },
  { id: 'r4', text: 'What has a neck but no head?', answer: 'BOTTLE', hint: 'Holds liquid' },
  { id: 'r5', text: 'What gets wetter the more it dries?', answer: 'TOWEL', hint: 'Found in bathrooms' },
  { id: 'r6', text: 'What can you catch but not throw?', answer: 'COLD', hint: 'Achoo!' },
  { id: 'r7', text: 'What has teeth but cannot bite?', answer: 'COMB', hint: 'Used on hair' },
  { id: 'r8', text: 'What has one eye but cannot see?', answer: 'NEEDLE', hint: 'Used for sewing' },
  { id: 'r9', text: 'What goes up but never comes down?', answer: 'AGE', hint: 'Everyone has one' },
  { id: 'r10', text: 'What has legs but doesn\'t walk?', answer: 'TABLE', hint: 'Found in kitchens' },
  { id: 'r11', text: 'What has a thumb and four fingers but is not alive?', answer: 'GLOVE', hint: 'Keeps hands warm' },
  { id: 'r12', text: 'What can travel around the world while staying in a corner?', answer: 'STAMP', hint: 'Found on mail' },
  { id: 'r13', text: 'What has many rings but no fingers?', answer: 'TREE', hint: 'Grows in forests' },
  { id: 'r14', text: 'What has a face and two hands but no arms or legs?', answer: 'CLOCK', hint: 'Tells the time' },
  { id: 'r15', text: 'What building has the most stories?', answer: 'LIBRARY', hint: 'Full of books' },
  { id: 'r16', text: 'What is full of holes but still holds water?', answer: 'SPONGE', hint: 'Used for cleaning' },
  { id: 'r17', text: 'I fly without wings. I cry without eyes. What am I?', answer: 'CLOUD', hint: 'In the sky' },
  { id: 'r18', text: 'What has a heart that doesn\'t beat?', answer: 'ARTICHOKE', hint: 'A vegetable' },
  { id: 'r19', text: 'What word becomes shorter when you add two letters?', answer: 'SHORT', hint: 'Think literally' },
  { id: 'r20', text: 'What has ears but cannot hear?', answer: 'CORN', hint: 'A crop' },
  { id: 'r21', text: 'What has a bark but no bite?', answer: 'TREE', hint: 'Grows tall' },
  { id: 'r22', text: 'What can fill a room but takes up no space?', answer: 'LIGHT', hint: 'Flip a switch' },
  { id: 'r23', text: 'What has words but never speaks?', answer: 'BOOK', hint: 'Read me' },
  { id: 'r24', text: 'What runs but never walks?', answer: 'WATER', hint: 'From a faucet' },
  { id: 'r25', text: 'What has a bed but never sleeps?', answer: 'RIVER', hint: 'Flows downstream' },
  { id: 'r26', text: 'What can you break without touching?', answer: 'PROMISE', hint: 'Keep your word' },
  { id: 'r27', text: 'What gets sharper the more you use it?', answer: 'BRAIN', hint: 'Think about it' },
  { id: 'r28', text: 'What is always in front of you but can\'t be seen?', answer: 'FUTURE', hint: 'Tomorrow' },
  { id: 'r29', text: 'What has cities, mountains, and water but no people?', answer: 'MAP', hint: 'Navigation tool' },
  { id: 'r30', text: 'What comes once in a minute, twice in a moment, but never in a thousand years?', answer: 'M', hint: 'A single letter' },
  { id: 'r31', text: 'What invention lets you look right through a wall?', answer: 'WINDOW', hint: 'Made of glass' },
  { id: 'r32', text: 'What has a bottom at the top?', answer: 'LEG', hint: 'Part of your body' },
  { id: 'r33', text: 'What can be cracked, made, told, and played?', answer: 'JOKE', hint: 'Ha ha!' },
  { id: 'r34', text: 'What kind of band never plays music?', answer: 'RUBBER', hint: 'Stretchy' },
  { id: 'r35', text: 'What has four wheels and flies?', answer: 'GARBAGE', hint: 'A smelly truck' },
  { id: 'r36', text: 'Where does Friday come before Thursday?', answer: 'DICTIONARY', hint: 'Alphabetical' },
  { id: 'r37', text: 'What month of the year has 28 days?', answer: 'ALL', hint: 'Every single one' },
  { id: 'r38', text: 'What is so fragile that saying its name breaks it?', answer: 'SILENCE', hint: 'Shhh!' },
  { id: 'r39', text: 'What can you hold in your left hand but not your right?', answer: 'ELBOW', hint: 'Part of your arm' },
  { id: 'r40', text: 'What tastes better than it smells?', answer: 'TONGUE', hint: 'In your mouth' },
  { id: 'r41', text: 'What has a spine but no bones?', answer: 'BOOK', hint: 'Found on shelves' },
  { id: 'r42', text: 'What can run but never walks, has a mouth but never talks?', answer: 'RIVER', hint: 'A body of water' },
  { id: 'r43', text: 'I have branches but no fruit, trunk, or leaves. What am I?', answer: 'BANK', hint: 'Money related' },
  { id: 'r44', text: 'What coat is best put on wet?', answer: 'PAINT', hint: 'Colorful' },
  { id: 'r45', text: 'What has a ring but no finger?', answer: 'PHONE', hint: 'Call me' },
  { id: 'r46', text: 'What goes up and down but doesn\'t move?', answer: 'STAIRS', hint: 'Step by step' },
  { id: 'r47', text: 'What is cut on a table but never eaten?', answer: 'CARDS', hint: 'Deck of fun' },
  { id: 'r48', text: 'What has an eye but cannot see?', answer: 'STORM', hint: 'Wild weather' },
  { id: 'r49', text: 'What kind of cup doesn\'t hold water?', answer: 'CUPCAKE', hint: 'Sweet treat' },
  { id: 'r50', text: 'What has a head, a tail, is brown, and has no legs?', answer: 'PENNY', hint: 'One cent' },

  // --- Batch 2: 200 more family-friendly riddles ---
  { id: 'r51', text: 'What has hands but can\'t hold anything?', answer: 'CLOCK', hint: 'Tick tock' },
  { id: 'r52', text: 'What has a tongue but cannot taste?', answer: 'SHOE', hint: 'Worn on feet' },
  { id: 'r53', text: 'What has a head but never weeps, has a bed but never sleeps?', answer: 'NAIL', hint: 'Hit with a hammer' },
  { id: 'r54', text: 'What goes through towns and over hills but never moves?', answer: 'ROAD', hint: 'Drive on it' },
  { id: 'r55', text: 'What belongs to you but others use it more than you do?', answer: 'NAME', hint: 'Identity' },
  { id: 'r56', text: 'What has a cap but no head?', answer: 'MUSHROOM', hint: 'Grows in damp places' },
  { id: 'r57', text: 'What kind of tree can you carry in your hand?', answer: 'PALM', hint: 'Also a body part' },
  { id: 'r58', text: 'What breaks yet never falls, and what falls yet never breaks?', answer: 'DAWN', hint: 'Start of a day' },
  { id: 'r59', text: 'What has 88 keys but can\'t open a single door?', answer: 'PIANO', hint: 'Musical instrument' },
  { id: 'r60', text: 'What gets bigger the more you take away from it?', answer: 'HOLE', hint: 'Dig one' },
  { id: 'r61', text: 'What has roots that nobody sees, is taller than trees, yet never grows?', answer: 'MOUNTAIN', hint: 'Very tall land' },
  { id: 'r62', text: 'What can be seen in the middle of March and April but not at the beginning or end?', answer: 'R', hint: 'A single letter' },
  { id: 'r63', text: 'What do you throw out when you want to use it but take in when you don\'t?', answer: 'ANCHOR', hint: 'Used on boats' },
  { id: 'r64', text: 'I have lakes with no water, mountains with no stone, and cities with no buildings. What am I?', answer: 'MAP', hint: 'Paper guide' },
  { id: 'r65', text: 'What falls but never gets hurt?', answer: 'RAIN', hint: 'Wet weather' },
  { id: 'r66', text: 'What can go up a chimney down but not down a chimney up?', answer: 'UMBRELLA', hint: 'Keeps you dry' },
  { id: 'r67', text: 'What has legs but cannot walk?', answer: 'CHAIR', hint: 'Sit on it' },
  { id: 'r68', text: 'What has wheels and flies but is not an aircraft?', answer: 'GARBAGE', hint: 'A smelly truck' },
  { id: 'r69', text: 'What starts with T, ends with T, and has T in it?', answer: 'TEAPOT', hint: 'Brew a cup' },
  { id: 'r70', text: 'What has a lock but no door?', answer: 'PADLOCK', hint: 'Security device' },
  { id: 'r71', text: 'What can honk without a horn?', answer: 'GOOSE', hint: 'A bird' },
  { id: 'r72', text: 'What has 13 hearts but no other organs?', answer: 'DECK', hint: 'Playing cards' },
  { id: 'r73', text: 'What room can no one enter?', answer: 'MUSHROOM', hint: 'Not really a room' },
  { id: 'r74', text: 'What word is spelled wrong in every dictionary?', answer: 'WRONG', hint: 'Think literally' },
  { id: 'r75', text: 'What fruit can you never cheer up?', answer: 'BLUEBERRY', hint: 'A sad color' },
  { id: 'r76', text: 'What is always coming but never arrives?', answer: 'TOMORROW', hint: 'The next day' },
  { id: 'r77', text: 'What has a bell but is not a church?', answer: 'DOORBELL', hint: 'Ding dong' },
  { id: 'r78', text: 'What has lots of eyes but cannot see?', answer: 'POTATO', hint: 'A vegetable' },
  { id: 'r79', text: 'What is tall when it\'s young and short when it\'s old?', answer: 'CANDLE', hint: 'Burns bright' },
  { id: 'r80', text: 'What runs all around a backyard yet never moves?', answer: 'FENCE', hint: 'Boundary marker' },
  { id: 'r81', text: 'What has hands but can\'t clap?', answer: 'CLOCK', hint: 'Keeps time' },
  { id: 'r82', text: 'What has a thumb and four fingers but is not a hand?', answer: 'GLOVE', hint: 'Winter wear' },
  { id: 'r83', text: 'What is black when you buy it, red when you use it, and gray when you throw it away?', answer: 'CHARCOAL', hint: 'For grilling' },
  { id: 'r84', text: 'What has needles but doesn\'t sew?', answer: 'PINE', hint: 'A type of tree' },
  { id: 'r85', text: 'What bow can\'t be tied?', answer: 'RAINBOW', hint: 'Colorful arc' },
  { id: 'r86', text: 'What building has the most floors?', answer: 'LIBRARY', hint: 'Full of stories' },
  { id: 'r87', text: 'What can you keep after giving to someone?', answer: 'WORD', hint: 'Keep your...' },
  { id: 'r88', text: 'What month has 28 days?', answer: 'ALL', hint: 'Every one of them' },
  { id: 'r89', text: 'What has a face but can\'t smile?', answer: 'CLOCK', hint: 'Tells time' },
  { id: 'r90', text: 'What can you place in a barrel to make it lighter?', answer: 'HOLE', hint: 'An empty space' },
  { id: 'r91', text: 'What disappears as soon as you say its name?', answer: 'SILENCE', hint: 'Quiet!' },
  { id: 'r92', text: 'What is harder to catch the faster you run?', answer: 'BREATH', hint: 'Inhale, exhale' },
  { id: 'r93', text: 'What kind of coat can only be put on when wet?', answer: 'PAINT', hint: 'Colorful layer' },
  { id: 'r94', text: 'What instrument can you hear but not see or touch?', answer: 'VOICE', hint: 'You use it to speak' },
  { id: 'r95', text: 'What has a door but no house?', answer: 'CABINET', hint: 'Kitchen furniture' },
  { id: 'r96', text: 'What is easy to get into but hard to get out of?', answer: 'TROUBLE', hint: 'Uh oh' },
  { id: 'r97', text: 'What goes in the water black and comes out red?', answer: 'LOBSTER', hint: 'A seafood dish' },
  { id: 'r98', text: 'What has to be broken before you can use it?', answer: 'EGG', hint: 'Breakfast food' },
  { id: 'r99', text: 'What goes up and down stairs without moving?', answer: 'CARPET', hint: 'Floor covering' },
  { id: 'r100', text: 'What has a crown but is not a king?', answer: 'TOOTH', hint: 'In your mouth' },
  { id: 'r101', text: 'What room do ghosts avoid?', answer: 'LIVING', hint: 'The ___ room' },
  { id: 'r102', text: 'What is at the end of a rainbow?', answer: 'W', hint: 'A single letter' },
  { id: 'r103', text: 'What can you serve but never eat?', answer: 'TENNIS', hint: 'A sport' },
  { id: 'r104', text: 'What has ears but cannot hear?', answer: 'CORN', hint: 'A yellow crop' },
  { id: 'r105', text: 'What has a neck but no head?', answer: 'GUITAR', hint: 'A musical instrument' },
  { id: 'r106', text: 'What goes up but never goes down?', answer: 'AGE', hint: 'Birthdays add to it' },
  { id: 'r107', text: 'What kind of room has no walls or corners?', answer: 'MUSHROOM', hint: 'Fungi' },
  { id: 'r108', text: 'What can you fill with empty hands?', answer: 'GLOVE', hint: 'Finger covering' },
  { id: 'r109', text: 'What is lighter than air but can\'t be held for ten minutes?', answer: 'BREATH', hint: 'In and out' },
  { id: 'r110', text: 'What can fly without wings?', answer: 'TIME', hint: 'It passes' },
  { id: 'r111', text: 'What can you not keep until you give it?', answer: 'PROMISE', hint: 'A pledge' },
  { id: 'r112', text: 'What is bought by the yard and worn by the foot?', answer: 'CARPET', hint: 'Floor covering' },
  { id: 'r113', text: 'What has a single eye but cannot see?', answer: 'NEEDLE', hint: 'Thread goes through it' },
  { id: 'r114', text: 'What starts with an E but only has one letter in it?', answer: 'ENVELOPE', hint: 'Holds mail' },
  { id: 'r115', text: 'What can be heard and caught but never seen?', answer: 'REMARK', hint: 'A comment' },
  { id: 'r116', text: 'What dress can you never wear?', answer: 'ADDRESS', hint: 'Where you live' },
  { id: 'r117', text: 'What has a bank but no money?', answer: 'RIVER', hint: 'Flowing water' },
  { id: 'r118', text: 'What do you bury when it\'s alive and dig up when it\'s dead?', answer: 'PLANT', hint: 'Green and leafy' },
  { id: 'r119', text: 'What turns everything around but does not move?', answer: 'MIRROR', hint: 'Reflects' },
  { id: 'r120', text: 'What has spaces but no room?', answer: 'KEYBOARD', hint: 'You type on it' },
  { id: 'r121', text: 'What body of water can you carry in your hand?', answer: 'POOL', hint: 'A small body of water' },
  { id: 'r122', text: 'What can be long or short, grown or bought, painted or bare?', answer: 'NAIL', hint: 'On your finger' },
  { id: 'r123', text: 'What can make an octopus laugh?', answer: 'TENTACLES', hint: 'Tickling arms' },
  { id: 'r124', text: 'What has a head and a tail but nothing in between?', answer: 'COIN', hint: 'Flip it' },
  { id: 'r125', text: 'What side of a cat has the most fur?', answer: 'OUTSIDE', hint: 'Not the inside' },
  { id: 'r126', text: 'What gets sharper the more you use it?', answer: 'BRAIN', hint: 'Your mind' },
  { id: 'r127', text: 'What wears a cap but has no head?', answer: 'BOTTLE', hint: 'Twist it off' },
  { id: 'r128', text: 'What comes down but never goes up?', answer: 'RAIN', hint: 'Wet drops' },
  { id: 'r129', text: 'What did the ocean say to the shore?', answer: 'WAVE', hint: 'A greeting' },
  { id: 'r130', text: 'What runs but never tires?', answer: 'WATER', hint: 'H2O' },
  { id: 'r131', text: 'What kind of ship has two mates but no captain?', answer: 'COURTSHIP', hint: 'Romance' },
  { id: 'r132', text: 'What is full when it\'s used and empty when it\'s at rest?', answer: 'SHOE', hint: 'Worn on feet' },
  { id: 'r133', text: 'What can be open or closed but not a door?', answer: 'BOOK', hint: 'Read it' },
  { id: 'r134', text: 'What can you catch but not throw?', answer: 'COLD', hint: 'Sneezy' },
  { id: 'r135', text: 'What do you call a fish without eyes?', answer: 'FSH', hint: 'Remove the I\'s' },
  { id: 'r136', text: 'What is as light as a feather but the strongest person can\'t hold it for long?', answer: 'BREATH', hint: 'Inhale deeply' },
  { id: 'r137', text: 'What has four legs in the morning, two at noon, and three at night?', answer: 'HUMAN', hint: 'The riddle of the Sphinx' },
  { id: 'r138', text: 'What has many keys but can\'t open any lock?', answer: 'KEYBOARD', hint: 'Computer input' },
  { id: 'r139', text: 'What flies all day but never goes anywhere?', answer: 'FLAG', hint: 'Waves in the wind' },
  { id: 'r140', text: 'What gets broken if it\'s not kept?', answer: 'PROMISE', hint: 'Your word' },
  { id: 'r141', text: 'What can point in every direction but can\'t reach anything?', answer: 'COMPASS', hint: 'Navigation tool' },
  { id: 'r142', text: 'What do you call a snowman in summer?', answer: 'PUDDLE', hint: 'Melted' },
  { id: 'r143', text: 'What has a foot but no legs?', answer: 'SNAIL', hint: 'Slimy creature' },
  { id: 'r144', text: 'What can be swallowed or can swallow you?', answer: 'PRIDE', hint: 'An emotion' },
  { id: 'r145', text: 'What has a bark but no bite?', answer: 'TREE', hint: 'Wooden' },
  { id: 'r146', text: 'What can go through a glass without breaking it?', answer: 'LIGHT', hint: 'Shines through' },
  { id: 'r147', text: 'What gets wetter the more it dries?', answer: 'TOWEL', hint: 'Bath accessory' },
  { id: 'r148', text: 'What cup can never hold water?', answer: 'CUPCAKE', hint: 'Frosted treat' },
  { id: 'r149', text: 'What begins with T, finishes with T, and has tea in it?', answer: 'TEAPOT', hint: 'Brew inside' },
  { id: 'r150', text: 'What kind of music do rabbits like?', answer: 'HIP', hint: '___-hop' },
  { id: 'r151', text: 'What vegetable is cool even when hot?', answer: 'PEPPER', hint: 'Spicy' },
  { id: 'r152', text: 'What bird can write?', answer: 'PEN', hint: 'Also a writing tool' },
  { id: 'r153', text: 'What animal can you always find at a baseball game?', answer: 'BAT', hint: 'Flies at night' },
  { id: 'r154', text: 'What rock group has four men that don\'t sing?', answer: 'RUSHMORE', hint: 'Presidential mountain' },
  { id: 'r155', text: 'What can be whole, half, or quarter but is not a number?', answer: 'MOON', hint: 'Night sky' },
  { id: 'r156', text: 'What has a ring but no finger?', answer: 'PHONE', hint: 'Call someone' },
  { id: 'r157', text: 'What tastes better than it smells?', answer: 'TONGUE', hint: 'Taste organ' },
  { id: 'r158', text: 'What has four fingers and a thumb but isn\'t alive?', answer: 'GLOVE', hint: 'Hand cover' },
  { id: 'r159', text: 'What has legs but can\'t walk?', answer: 'TABLE', hint: 'Furniture' },
  { id: 'r160', text: 'What has a neck but no head?', answer: 'BOTTLE', hint: 'Pour from it' },
  { id: 'r161', text: 'What can you catch but cannot throw?', answer: 'COLD', hint: 'A sickness' },
  { id: 'r162', text: 'What is always on its way but never arrives?', answer: 'TOMORROW', hint: 'Always a day away' },
  { id: 'r163', text: 'What is brown and sticky?', answer: 'STICK', hint: 'Found on the ground' },
  { id: 'r164', text: 'What do you call a sleeping dinosaur?', answer: 'DINO', hint: 'A dino-snore' },
  { id: 'r165', text: 'What has a tail and a head but no body?', answer: 'COIN', hint: 'Spare change' },
  { id: 'r166', text: 'What gets smaller every time it takes a bath?', answer: 'SOAP', hint: 'Cleaning product' },
  { id: 'r167', text: 'What do you call a bear with no teeth?', answer: 'GUMMY', hint: 'A candy type' },
  { id: 'r168', text: 'What is orange and sounds like a parrot?', answer: 'CARROT', hint: 'A vegetable' },
  { id: 'r169', text: 'What stays in one corner but travels all around the world?', answer: 'STAMP', hint: 'On an envelope' },
  { id: 'r170', text: 'What has a spine but no bones?', answer: 'BOOK', hint: 'Has pages' },
  { id: 'r171', text: 'What do lazy dogs do for fun?', answer: 'CHASE', hint: 'They ___ their tails' },
  { id: 'r172', text: 'What is always in front of you but can\'t be seen?', answer: 'FUTURE', hint: 'What comes next' },
  { id: 'r173', text: 'What can you hold without touching it?', answer: 'BREATH', hint: 'Don\'t exhale' },
  { id: 'r174', text: 'What has a sole but is not alive?', answer: 'SHOE', hint: 'Footwear' },
  { id: 'r175', text: 'What can travel the world while staying in a corner?', answer: 'STAMP', hint: 'Postage' },
  { id: 'r176', text: 'What has a horn but does not honk?', answer: 'RHINO', hint: 'Big animal' },
  { id: 'r177', text: 'What flies when it\'s born, lies when it\'s alive, and runs when it\'s dead?', answer: 'SNOWFLAKE', hint: 'Winter crystal' },
  { id: 'r178', text: 'What word looks the same backwards and upside down?', answer: 'SWIMS', hint: 'Pool activity' },
  { id: 'r179', text: 'What has stripes but is not a zebra?', answer: 'TIGER', hint: 'Big cat' },
  { id: 'r180', text: 'What coat is always wet when you put it on?', answer: 'PAINT', hint: 'A fresh layer' },
  { id: 'r181', text: 'What do bees make?', answer: 'HONEY', hint: 'Sweet and golden' },
  { id: 'r182', text: 'What object has keys that open no locks, space but no room, and you can enter but can\'t go inside?', answer: 'KEYBOARD', hint: 'Computer input device' },
  { id: 'r183', text: 'What can be measured but has no length, width, or height?', answer: 'TIME', hint: 'Tick tock' },
  { id: 'r184', text: 'What has one hundred limbs but cannot walk?', answer: 'TREE', hint: 'Branches' },
  { id: 'r185', text: 'What has a lake but no fish?', answer: 'MAP', hint: 'Drawn to scale' },
  { id: 'r186', text: 'What is the hardest key to turn?', answer: 'DONKEY', hint: 'An animal' },
  { id: 'r187', text: 'What has a blade but is not a knife?', answer: 'GRASS', hint: 'Green ground cover' },
  { id: 'r188', text: 'What can be cracked but is not an egg?', answer: 'CODE', hint: 'Secret message' },
  { id: 'r189', text: 'What gets harder to catch the faster you run?', answer: 'BREATH', hint: 'Panting' },
  { id: 'r190', text: 'What falls in winter but never gets hurt?', answer: 'SNOW', hint: 'Cold and white' },
  { id: 'r191', text: 'What has teeth but no mouth?', answer: 'SAW', hint: 'A cutting tool' },
  { id: 'r192', text: 'What do you call a boomerang that doesn\'t come back?', answer: 'STICK', hint: 'Just a piece of wood' },
  { id: 'r193', text: 'What animal turns about 200 times around its axis after it dies?', answer: 'CHICKEN', hint: 'Rotisserie' },
  { id: 'r194', text: 'What has a mouth but never eats?', answer: 'RIVER', hint: 'Where it meets the sea' },
  { id: 'r195', text: 'What runs around the whole yard without moving?', answer: 'FENCE', hint: 'Keeps things in' },
  { id: 'r196', text: 'What can you break without touching?', answer: 'RECORD', hint: 'A new high score' },
  { id: 'r197', text: 'What has many teeth but cannot eat?', answer: 'COMB', hint: 'For your hair' },
  { id: 'r198', text: 'What goes up when the rain comes down?', answer: 'UMBRELLA', hint: 'Rain gear' },
  { id: 'r199', text: 'What do you call a story about a broken pencil?', answer: 'POINTLESS', hint: 'No sharp tip' },
  { id: 'r200', text: 'What do sea monsters eat?', answer: 'FISH', hint: 'Swims in the sea' },
  { id: 'r201', text: 'What can wave but has no hands?', answer: 'FLAG', hint: 'On a pole' },
  { id: 'r202', text: 'What building has the most rooms?', answer: 'HOTEL', hint: 'You book a stay' },
  { id: 'r203', text: 'What do snowmen eat for breakfast?', answer: 'FROSTED', hint: '___ flakes' },
  { id: 'r204', text: 'What do you break every time you name it?', answer: 'SILENCE', hint: 'Be quiet' },
  { id: 'r205', text: 'What time of day is spelled the same forwards and backwards?', answer: 'NOON', hint: 'Middle of the day' },
  { id: 'r206', text: 'What is easy to lift but hard to throw?', answer: 'FEATHER', hint: 'From a bird' },
  { id: 'r207', text: 'What has cities but no houses, forests but no trees, and water but no fish?', answer: 'MAP', hint: 'A flat guide' },
  { id: 'r208', text: 'What has wings but cannot fly?', answer: 'PENGUIN', hint: 'Waddles on ice' },
  { id: 'r209', text: 'What do you throw out when you need it and bring in when you don\'t?', answer: 'ANCHOR', hint: 'Keeps boats still' },
  { id: 'r210', text: 'What has spots but is not sick?', answer: 'DICE', hint: 'Roll them' },
  { id: 'r211', text: 'What has four legs but only one foot?', answer: 'BED', hint: 'Sleep on it' },
  { id: 'r212', text: 'What is so delicate that saying its name breaks it?', answer: 'SILENCE', hint: 'Hush' },
  { id: 'r213', text: 'What rises in the morning and waves all day?', answer: 'FLAG', hint: 'Patriotic symbol' },
  { id: 'r214', text: 'What can fill a room but doesn\'t take up any space?', answer: 'LIGHT', hint: 'Turn it on' },
  { id: 'r215', text: 'What has an end but no beginning, a home but no family, and space but no room?', answer: 'KEYBOARD', hint: 'Type on it' },
  { id: 'r216', text: 'What creature walks on four legs in the morning, two at noon, and three in the evening?', answer: 'HUMAN', hint: 'Ancient riddle' },
  { id: 'r217', text: 'What has a golden head and a golden tail but no body?', answer: 'COIN', hint: 'Treasure' },
  { id: 'r218', text: 'What can be big, white, dirty, or sweet?', answer: 'LIE', hint: 'Not the truth' },
  { id: 'r219', text: 'What is it that given one you\'ll have either two or none?', answer: 'CHOICE', hint: 'A decision' },
  { id: 'r220', text: 'What weighs more — a pound of feathers or a pound of bricks?', answer: 'SAME', hint: 'Equal weight' },
  { id: 'r221', text: 'What has a head but cannot think?', answer: 'NAIL', hint: 'Hammer it' },
  { id: 'r222', text: 'What grows when it eats but dies when it drinks?', answer: 'FIRE', hint: 'Hot and bright' },
  { id: 'r223', text: 'What can you see once in a year, twice in a week, but never in a day?', answer: 'E', hint: 'A single letter' },
  { id: 'r224', text: 'What do you bury when it\'s alive and dig up when it\'s dead?', answer: 'PLANT', hint: 'Roots and leaves' },
  { id: 'r225', text: 'What has a handle but no door?', answer: 'CUP', hint: 'Drink from it' },
  { id: 'r226', text: 'What is always running but has no legs?', answer: 'FAUCET', hint: 'Drip drip' },
  { id: 'r227', text: 'What disappears the moment you say its name?', answer: 'SILENCE', hint: 'No noise' },
  { id: 'r228', text: 'What has a head, a foot, and four legs?', answer: 'BED', hint: 'Nap time' },
  { id: 'r229', text: 'What can be drawn but never seen?', answer: 'BREATH', hint: 'Take a deep one' },
  { id: 'r230', text: 'What do you find at the end of every line?', answer: 'E', hint: 'Last letter' },
  { id: 'r231', text: 'What is something you can make that no one can see?', answer: 'NOISE', hint: 'Loud or soft' },
  { id: 'r232', text: 'What always follows you but can never be caught?', answer: 'SHADOW', hint: 'Needs light' },
  { id: 'r233', text: 'What is red, white, and blue?', answer: 'FLAG', hint: 'American symbol' },
  { id: 'r234', text: 'What can be played but is not a game?', answer: 'MUSIC', hint: 'Sweet melodies' },
  { id: 'r235', text: 'What do you call a fish that has no eyes?', answer: 'FSH', hint: 'Remove the I' },
  { id: 'r236', text: 'What goes up and down but stays in the same place?', answer: 'STAIRS', hint: 'Climb them' },
  { id: 'r237', text: 'What can be written, spoken, and broken but never seen?', answer: 'PROMISE', hint: 'Your word' },
  { id: 'r238', text: 'What has leaves but is not a tree?', answer: 'BOOK', hint: 'Flip through them' },
  { id: 'r239', text: 'What is found in the center of gravity?', answer: 'V', hint: 'A single letter' },
  { id: 'r240', text: 'What kind of dog doesn\'t bite or bark?', answer: 'HOTDOG', hint: 'Eat it!' },
  { id: 'r241', text: 'What can be read but never heard?', answer: 'BOOK', hint: 'Silent pages' },
  { id: 'r242', text: 'What has a wall but is not a building?', answer: 'CELL', hint: 'Living unit' },
  { id: 'r243', text: 'What can be big or small, come from far or near, but you can never actually touch it?', answer: 'SOUND', hint: 'Listen closely' },
  { id: 'r244', text: 'What has many needles but can\'t sew?', answer: 'PINE', hint: 'Evergreen tree' },
  { id: 'r245', text: 'What can be split, shared, or taken whole?', answer: 'OPINION', hint: 'Point of view' },
  { id: 'r246', text: 'What stretches without getting bigger?', answer: 'TIME', hint: 'It drags' },
  { id: 'r247', text: 'What has wings, a tail, and no body?', answer: 'PLANE', hint: 'Flies in the sky' },
  { id: 'r248', text: 'What kind of key opens a banana?', answer: 'MONKEY', hint: 'An animal' },
  { id: 'r249', text: 'What can be eaten but never goes bad?', answer: 'WORDS', hint: 'Eat your...' },
  { id: 'r250', text: 'What runs in a garden but has no legs?', answer: 'HOSE', hint: 'Waters plants' },
];

export const MAX_RIDDLE_ANSWER_LENGTH = 10;
export const RIDDLE_MAX_GUESSES = 5;
