name = "lamo-trivia-api"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[durable_objects]
bindings = [
  { name = "GAME_LOBBY", class_name = "GameLobby" },
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameLobby", "GameRoom"]

[[kv_namespaces]]
binding = "TRIVIA_KV"
id = "764eda89270249808b1dede3c375f033"

[vars]
FRONTEND_URL = "https://lamo-trivia.pages.dev"
